[package]
name = "pxe"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smoltcp = { path = "external/smoltcp"}
getopts = "=0.2"
log = { version = "=0.4.4" }
env_logger = "=0.5"
uuid = "=0.8.2"
