[package]
name = "bootloader"
version = "0.1.0"
authors = ["Luis Hebendanz <luis.nixos@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uart_16550 = { path = "../uart_16550"  }
x86_64 = { path = "../x86_64", features=["instructions"]  }
spin = "0.6.0"
log = {version = "0.4.11", features = ["release_max_level_trace"] }
multiboot2 = "0.10.1"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[build-dependencies]
llvm-tools = { version = "0.1" }

[features]
binary = []

[package.metadata.bootloader]
target = "i686-unknown-linux-gnu.json"
build-std = "core"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true
