[package]
name = "dyn_frame_alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
simple_logger = "=1.13.0"
log = "=0.4.14"
