
[package]
name = "uart_16550"
version = "0.2.10"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>", "Philipp Oppermann <dev@phil-opp.com>"]
description = "Minimal support for uart_16550 serial output."
license = "MIT"
repository = "https://github.com/rust-osdev/uart_16550"
edition = "2018"

[dependencies]
bitflags = "1.1.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { path="../x86_64", default-features = false, features = ["instructions"] }


[target.'cfg(target_arch = "x86")'.dependencies]
x86 = { path="../x86", default-features = false, features = ["instructions"] }

[features]
default = [ "nightly" ]
stable = [ "x86_64/external_asm" ]
nightly = [ "x86_64/nightly" ]

[package.metadata.release]
no-dev-version = true
pre-release-replacements = [
    { file="Changelog.md", search="# Unreleased", replace="# Unreleased\n\n# {{version}} â€“ {{date}}", exactly=1 },
]
pre-release-commit-message = "Release version {{version}}"
